### ISSUE TITLE
Access soft deleted in polymorphic association

### ISSUE THREAD

**Issue by nunosilva800** [rubysherpas/paranoia#172]
In a Rails 3 app with acts_as_paranoid, I have:

`belongs_to :reportable, :polymorphic => true, :with_deleted => true`

How can I convert this to paranoia "syntax"?

**Comment by radar** [comment]
I would advise that you override the getter method, like what's done [here in Spree](https://github.com/spree/spree/blob/master/core/app/models/spree/line_item.rb#L98-L100).

**Comment by nunosilva800** [comment]
The thing is: its a **polymorphic** association, how do I override? Would this work?

```
def reportable
  reportable_type.constantize.unscoped { super }
end
```

**Comment by radar** [comment]
Oh yeah, that's right. I think that would work.

**Comment by chadwilken** [comment]
It looks like you can change the polymorphic relationship to have a scope as the second parameter and it will work:
```
belongs_to :commentable, -> { with_deleted }, polymorphic: true
```

**Comment by chadwilken** [comment]
Is there a better way to pass a scope to a polymorphic relationship?

**Comment by eveevans** [comment]
@chadwilken  How to handle when not all the polymorfic associations have the with_deleted scope?

**Comment by chadwilken** [comment]
@eveevans that is a trickier one. The hacky thing to do would be to create a concern or add a scope that aliases `all` to `with_deleted` so that it still works. You can also experiment with the optional scope you can pass to the `belongs_to` as shown [here](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to-label-Scopes). You may be able to do some reflection and figure out if it is a soft-deleted record or not.

**Comment by eveevans** [comment]
Thanks @chadwilken 
At the end I did this, and works perfect: 

`belongs_to :commentable, -> { try(:with_deleted) || unscoped }, polymorphic: true  `
