### ISSUE TITLE
`delete_all` does not work on ActiveRecord::Relation objects

### ISSUE THREAD

**Issue by unimatrixZxero** [rubysherpas/paranoia#312]
The current implementation does not capture the `delete_all` called on `ActiveRecord::Relation` object. For example when you call `ParanoidModel.where(column: value).delete_all` it is executing the original `delete_all` on `ActiveRecord::Relation` not one defined in `Paranoia`.

Test that shows broken behavior:

```
def test_delete_all_with_scope
    model = ParanoidModel
    count = 3
    models = count.times.map { model.new }
    assert_equal 0, model.count
    models.each(&:save!)

    assert_equal count, model.count
    model.where(parent_model_id: nil).delete_all

    assert_equal 0, model.count
    assert_equal count, model.with_deleted.count

    assert model.with_deleted.all?(&:deleted?)
  end
```

```
  1) Failure:
ParanoiaTest#test_delete_all_with_scope [test/paranoia_test.rb:948]:
Expected: 3
  Actual: 0
```

While this quick fix passes that test...

```
module ActiveRecord
  class Relation
    def delete_all(conditions = nil)
      return super unless model.paranoid?
      model.update_all(model.new.send :paranoia_destroy_attributes)
    end
  end
end
```

... it **DOESN'T** work for the whole suite, really_delete and restores will go into infinite loops currently. I'm still looking into a fix but I thought I'd share it here incase anyone wants to join the effort, and to make people aware of the bug.

**Comment by dvdchr** [comment]
Aside from relations, this also happens for `ActiveRecord::Association` objects, e.g.:

``` ruby
def test_delete_all_association
  model = ParentModel
  parent = model.create
  count = 3
  count.times.map { parent.related_models.create }

  assert_equal count, parent.related_models.count
  parent.related_models.delete_all

  assert_equal 0, parent.related_models.count
  assert_equal count, parent.related_models.with_deleted.count
end
```

The test yields:

```
  1) Failure:
ParanoiaTest#test_delete_all_association [test/paranoia_test.rb:947]:
Expected: 3
  Actual: 0
```

**Comment by dvdchr** [comment]
I've spent a bit tracing this issue. Turns out, the original `delete` method turns the record into an `ActiveRecord::Relation` and then calls `delete_all`:

``` ruby
# active_record/persistence.rb
def delete
  self.class.delete(id) if persisted?
  @destroyed = true
  freeze
end
```

...Which is why the tests will break if we override `ActiveRecord::Relation#delete_all`. By simply checking `.paranoid?` is not sufficient, because the main problem is we do not know whether the original call was a soft delete (`record.delete`) or a permanent delete (`record.really_delete`). 

Currently, I  `alias :really_delete_all :delete_all` on `ActiveRecord::Relation`, and implement `really_delete` to call the `really_delete_all` method on the relation object. 

``` ruby
  def really_delete
    self.class.where(id: id).really_delete_all if persisted?
    @destroyed = true
    freeze
  end
```

The `delete_all` is then overridden with `prepend` (available on ruby version > 2) to actually check `model.paranoid?` (similar to @unimatrixZxero 's approach above, and the one in #265). This way, the overridden `delete_all` will only receive either non-paranoid models, or paranoid model with soft delete intention. In short, `delete_all` will soft delete, and `really_delete_all` will permanently delete records.

The approach above works for `ActiveRecord::Relation` and also `ActiveRecord::Association`, but only with `dependent: :destroy` (i.e. very related). What this does is soft delete dependent records but their relationships (foreign keys) are kept. This is to enable calls such as:

```
parent.very_related_models.only_deleted
```

to return soft deleted records. The problem is with non-dependent records (e.g. `has_many :related_models`). ActiveRecord does this by deleting the foreign key on the related records. This behavior is described on the method below:

``` ruby
# has_many_association.rb
def delete_count(method, scope)
  if method == :delete_all
    scope.delete_all
  else
    scope.update_all(reflection.foreign_key => nil)
  end
end
```

In my opinion, when we want to soft delete dependent and non-dependent records, they should have the same behavior (i.e. mark them as deleted & keep foreign key). The bottom line is, we need to override several ActiveRecord methods and more importantly define clear expectations when we want to soft delete relations / associations.

Thoughts?

**Comment by BenMorganIO** [comment]
@unimatrixZxero @davidchristiandy please see: https://github.com/rubysherpas/paranoia/issues/304 and https://github.com/rubysherpas/paranoia/pull/132

Can you confirm that this is related? Going to close for now since I have a feeling it is. Let me know why it isn't and I'll reopen it :)
