### ISSUE TITLE
Support for 5.2

### ISSUE THREAD

**Issue by kapso** [rubysherpas/paranoia#438]
Is this support going to be added?

**Comment by jhawthorn** [comment]
Current git head supports Rails 5.2, gem will be released shortly.

**Comment by donatoaz** [comment]
Hi @jhawthorn is this new release still in plan? I have been using `gem "paranoia", :github => 'rubysherpas/paranoia', :ref => '1434cc672af77212658d70d437c0c7f8331e06e1'` ever since to get it working for Rails 5.2

I'm very limited as to knowledge for offering contribution, but if there is anything I could do to help, let me know.
