### ISSUE TITLE
CI seems broken?

### ISSUE THREAD

**Issue by jhawthorn** [rubysherpas/paranoia#464]
CI on this project seems non-working.

I wanted to merge https://github.com/rubysherpas/paranoia/pull/456 which looks to be in a great state... but CI hasn't started and it won't let me merge. (I have commit bit, rubygems ownership, but not _GitHub admin_ on this repo).

It looks like no CI builds have run in the last month https://travis-ci.org/rubysherpas/paranoia/pull_requests

@BenMorganIO do you have ownership bit on this repo 🙇? Is anything obviously wrong with our Travis integration? I no longer use this gem at work, but I'd like to release a new version for those who _really_ need the Rails 6.0 support.

Worst case I can fork this repo and cut a new rubygems release, but if we could keep this consolidated that would be best.

**Comment by BenMorganIO** [comment]
I don't have Github admin and I can't change up the TravisCI stuff. Went over to the Travis and it seems they think this project is not active: https://travis-ci.org/rubysherpas/paranoia

I tried to execute a custom build of `core` but received this message:

> Oops, something went wrong, please try again.

I honestly can't figure out how to get Travis to start again.

cc @radar who may be able to help.

**Comment by junaruga** [comment]
This is a site to raise this issue?
https://travis-ci.community/

**Comment by mberlanda** [comment]
@jhawthorn @BenMorganIO @radar 

Your project is still present on travis-ci.org but the integration has been deprecated

![image](https://user-images.githubusercontent.com/16099063/53885543-4c036c00-401e-11e9-826f-97f90aa2c585.png)

It looks like the last build travis was around 2 months ago.

My guess is that you integrated Travis using a Github Service instead of a Github App:

https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

They started a rollout at the end of last year to stop the support for Github Service integration.

If anybody has admin access to this repo, you should go to:

Settings/Integration & Services:

![image](https://user-images.githubusercontent.com/16099063/53885780-dd72de00-401e-11e9-98bd-a8a4e6eb2e45.png)

Let me know if you need some help to do it.
I was about to open a PR but it does not make a lot of sense now without the CI 😄

**Comment by BenMorganIO** [comment]
@mberlanda thanks for the info! That's probably what happened. Trouble is, I don't think @jhawthorn or I know who has admin access.

**Comment by BenMorganIO** [comment]
Since this is a part of the rubysherpas org, perhaps @sevenseacat may have access.

@sevenseacat you're the only one listed publicly that is a member of the organization.

**Comment by BenMorganIO** [comment]
Sent an email to contact@rubysherpas.com but it bounced...

> Address not found
> --
> Your message wasn't delivered to contact@rubysherpas.com because the domain rubysherpas.com couldn't be found. Check for typos or unnecessary spaces and try again.

**Comment by BenMorganIO** [comment]
```
$ whois rubysherpas.com
    Admin Email: https://whois.pairdomains.com/contact?domain=rubysherpas.com&type=admin
```

Sent an email using that form.

**Comment by sevenseacat** [comment]
hello! I'll have a look at it shortly :)

**Comment by sevenseacat** [comment]
Travis CI are in the middle of their migration for open source projects, from .org to .com - have emailed them to be included in the closed beta to get moved over, once that's done I can flick the switch on the Github App, which has been installed :)

**Comment by sevenseacat** [comment]
(it appears Ryan has given admin access on this repo to you now @jhawthorn and @BenMorganIO - let me know if you need anything else)

**Comment by sevenseacat** [comment]
Build is up and running again at https://travis-ci.com/rubysherpas/paranoia - atm it's failing due to something SQLite related, but it's running!
