### ISSUE TITLE
Retrieve associated belongs_to record without using with_deleted for belongs_to association

### ISSUE THREAD

**Issue by Anas-Shahid** [rubysherpas/paranoia#502]
Hi!
First of all, thank you for this amazing gem, it has helped me ALOT.
So, I'm trying to retrieve the soft-deleted belongs_to record without using `with_deleted` for the belongs_to association, as it would disturb the normal flow of the associations used elsewhere in the app.
Here's what I'm trying to do:
```
   class Leave < ApplicationRecord
       acts_as_paranoid
       
       belongs_to :user
   end

   class User < ApplicationRecord
       acts_as_paranoid
       
       has_many :leaves, dependent: :destroy
   end
```

I'm trying to retrieve the deleted User, from the deleted Leave like so:
```
   Leave.with_deleted.find(1).user.with_deleted
```

### Expected Behavior
    Retrieve the deleted user for the deleted leave.

### Actual Behavior
    Getting error: `undefined method `with_deleted' for nil:NilClass`
   
Though, I'm able to retrieve the deleted leave.

### Configuration
   `Ubuntu 20.04`
   `Rails 5.1.7`
   `Ruby 2.5.7`

Please guide me on what I'm doing wrong.

Thanks :slightly_smiling_face:

**Comment by ozzyaaron** [comment]
Just commenting here because I was looking at a similar issue. 

The quick fix is something like 

`belongs_to :user, -> { with_deleted }` 

or 

`belongs_to :user, -> { unscope(where: :deleted_at) }`

In my case I used the latter as I had a polymorphic `belongs_to` where not all polymorphic classes included the `with_deleted` scope. 

That being said I think if the User is deleted you probably don't want to included deleted users in a normal association like that.

In my experience having a separate association to include deleted items will serve better in the long run.

**Comment by Anas-Shahid** [comment]
@ozzyaaron - Thanks for the reply.

Yes, I agree with you to separate these associations.

**Comment by Anas-Shahid** [comment]
Can be achieved by following [this](https://github.com/rubysherpas/paranoia/issues/502#issuecomment-941204355).
