### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by mnifakram** [rubysherpas/paranoia#518]
Hello,

Steps to reproduce:

1. rails new test --dev --force
2. `rails generate scaffold User name username email`
3. `rails generate migration AddDeletedAtToUser deleted_at:datetime:index`
4. add `acts_as_paranoid` to `app/models/user.rb`
5. `rails c`
6. `User.first`

When trying to load a model that use this gem I got the following error `lib/active_record/scoping/default.rb:123:in default_scope': unknown keyword: :conditions (ArgumentError)`

Any ideas on how to quickly fix it or when support will be considered for Rails 7

Thank you so much for the great work done on this gem.

**Comment by ryanwi** [comment]
It appears the gem won't even install on Rails 7? 

```
  s.add_dependency 'activerecord', '>= 4.0', '< 6.2'
```

I am curious to know as well if this gem will be supporting Rails 7?

UPDATE: I see the https://github.com/rubysherpas/paranoia/pull/516 PR now, apologies for missing that.

**Comment by gordysc** [comment]
@mnifakram , I'd recommend forking the repository in the #516 PR while we wait on their PR to be merged. I hit the same issue as you and it was because bundler had resolved a much older version of this gem (1.2.0) which causes the unknown keyword error to occur. I'm using the rails7 branch of the PR from #516 and I haven't had any problems

**Comment by radar** [comment]
Done in v2.5.0.
